project:
  type: website
  output-dir: docs
  resources:
    - posts/CV_JoaquinCavieres.pdf
    - images/chart.jpg
    - images/hmat1.png

website:
  title: "Joaquin Cavieres"
  navbar:
    right:
      - research.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/jcavieresg
      - icon: twitter
        href: https://x.com/jcavieresg
      - text: "CV"
        href: posts/CV_JoaquinCavieres.pdf

format:
  html:
    theme: flatly
    css: styles.css
    number-sections: true
    number-equations: true
    bibliography: references.bib

editor: visual
